CITS3007 Project: p_and_p.c File Reference
p_and_p.c File Reference
#include <p_and_p.h>
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <pwd.h>
Macros
#define _POSIX_C_SOURCE 200809L
Functions
int saveItemDetails (const struct ItemDetails *arr, size_t nmemb, int fd)
A function that validates the data, opens the incomming file descriptor for writing and writes the data to the file.
int saveItemDetailsToPath (const struct ItemDetails *arr, size_t nmemb, const char *filename)
For Testing purposes only.
int loadItemDetails (struct ItemDetails **ptr, size_t *nmemb, int fd)
This function reads ItemDetails from a file descriptor, validates the data and stores it in the provided pointer.
int isValidName (const char *str)
This function checks if a string is a valid name.
int isValidMultiword (const char *str)
This function checks if a string is a valid multiword.
int isValidItemDetails (const struct ItemDetails *id)
This function checks if an itemDetail srtuct is valid.
int isValidCharacter (const struct Character *c)
This function checks whether a Character struct is valid It is valid iff all of its fields are valid the profession field must be a valid name field the name field must be a valid multi-word field the total number of items carried must not exceed MAX_ITEMS inventorySize must be less than or equal to MAX_ITEMS.
int saveCharacters (struct Character *arr, size_t nmemb, int fd)
This function validates the data, opens a file descriptor for writing, and writes the data to the file.
int loadCharacters (struct Character **ptr, size_t *nmemb, int fd)
This function reads Character from a file descriptor, validates the data and stores it in the incomming pointer.
int secureLoad (const char *filepath)
This function attempt to acquire appropriate permissions for opening the ItemDetails database and load the database from the specified file, and then call the function playgame() to which it should pass the loaded data and the number of items in the loaded data.
void playGame (struct ItemDetails *ptr, size_t nmemb)
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 10 of file p_and_p.c.
Function Documentation
saveItemDetails()
int saveItemDetails (const struct ItemDetails * arr, size_t nmemb, int fd)
A function that validates the data, opens the incomming file descriptor for writing and writes the data to the file.
It makes a copy of ItemDetails array and check the copy if it is valid by calling other isValidItemDetails. It returns 0 on success and 1 on failure.
Parameters
arr The array of ItemDetails to save.
nmemb The number of elements in the array.
fd The file descriptor to write to.
Returns
0 on success, 1 on failure.
Definition at line 38 of file p_and_p.c.
References isValidItemDetails().
Referenced by saveItemDetailsToPath().
saveItemDetailsToPath()
int saveItemDetailsToPath (const struct ItemDetails * arr, size_t nmemb, const char * filename)
For Testing purposes only.
This function saves an array of ItemDetails to a binary file. It first opens the file, then calls saveItemDetails to perform the actual data saving. After the data is saved, the file is closed.
Parameters
arr Pointer to the array of ItemDetails to be saved.
nmemb Number of elements in the array.
filename Path to the binary file where data will be saved.
Returns
0 on success, non-zero on failure.
Definition at line 95 of file p_and_p.c.
References saveItemDetails().
loadItemDetails()
int loadItemDetails (struct ItemDetails ** ptr, size_t * nmemb, int fd)
This function reads ItemDetails from a file descriptor, validates the data and stores it in the provided pointer.
It checks each filed in the struct if they pass valid functions. After passing, only copy the string up to null byte terminator and sanitizes bytes after the null bye. It returns 0 on success and 1 on failure.
Parameters
ptr Pointer to store the loaded data.
nmemb Number of elements loaded.
fd File descriptor to read from.
Returns
0 on success, 1 on failure.
Definition at line 119 of file p_and_p.c.
References ItemDetails::desc, isValidItemDetails(), and ItemDetails::name.
Referenced by secureLoad().
isValidName()
int isValidName (const char * str)
This function checks if a string is a valid name.
The incomming string should return true with function isgraph() Return 1 on success and 0 on failure.
Parameters
str The string to validate.
Returns
1 if valid, 0 if not.
Definition at line 195 of file p_and_p.c.
Referenced by isValidCharacter(), and isValidItemDetails().
isValidMultiword()
int isValidMultiword (const char * str)
This function checks if a string is a valid multiword.
The incomming parameter should return true with function isgraph() The incomming parameter is allowed to have spaces but not at the start or end Return 1 on success and 0 on failure.
Parameters
str The string to validate.
Returns
1 if valid, 0 if not.
Definition at line 227 of file p_and_p.c.
Referenced by isValidCharacter(), and isValidItemDetails().
isValidItemDetails()
int isValidItemDetails (const struct ItemDetails * id)
This function checks if an itemDetail srtuct is valid.
Calls isValidName and isValidMultiword to check struct fields validity. Return 1 on success and 0 on failure.
Parameters
id pointer to the item detail struct
Returns
1 if valid, 0 if not.
Definition at line 258 of file p_and_p.c.
References ItemDetails::desc, isValidMultiword(), isValidName(), ItemDetails::itemID, and ItemDetails::name.
Referenced by loadItemDetails(), and saveItemDetails().
isValidCharacter()
int isValidCharacter (const struct Character * c)
This function checks whether a Character struct is valid It is valid iff all of its fields are valid the profession field must be a valid name field the name field must be a valid multi-word field the total number of items carried must not exceed MAX_ITEMS inventorySize must be less than or equal to MAX_ITEMS.
Returns 1 if the struct is valid, and 0 if not.
Parameters
c Pointer to the Character struct to validate.
Returns
1 if valid, 0 if not.
Definition at line 289 of file p_and_p.c.
References ARISTOCRACY, Character::characterID, Character::inventory, Character::inventorySize, isValidMultiword(), isValidName(), MENDICANT, Character::name, Character::profession, ItemCarried::quantity, and Character::socialClass.
Referenced by loadCharacters(), and saveCharacters().
saveCharacters()
int saveCharacters (struct Character * arr, size_t nmemb, int fd)
This function validates the data, opens a file descriptor for writing, and writes the data to the file.
It is valid iff all character entries passes isValidCharacter() function It returns 0 on success and 1 on failure.
Parameters
arr The array of Character to save.
nmemb The number of elements in the array.
fd The file descriptor to write to.
Returns
0 on success, 1 on failure.
Definition at line 344 of file p_and_p.c.
References isValidCharacter().
loadCharacters()
int loadCharacters (struct Character ** ptr, size_t * nmemb, int fd)
This function reads Character from a file descriptor, validates the data and stores it in the incomming pointer.
It created and allocates space depending on the number of Characters to load Each characters read must pass isValidCharacter() validation It returns 0 on success and 1 on failure.
Parameters
ptr Pointer to store the loaded data.
nmemb Number of elements loaded.
fd File descriptor to read from.
Returns
0 on success, 1 on failure.
Definition at line 398 of file p_and_p.c.
References isValidCharacter(), Character::name, and Character::profession.
secureLoad()
int secureLoad (const char * filepath)
This function attempt to acquire appropriate permissions for opening the ItemDetails database and load the database from the specified file, and then call the function playgame() to which it should pass the loaded data and the number of items in the loaded data.
It returns 0 on success, 1 on deserialization error, and 2 on permission or other errors.
Parameters
filepath The path to the file to load data from.
Returns
0 on success, 1 on deserialization error, 2 on permission or other errors.
Definition at line 478 of file p_and_p.c.
References loadItemDetails(), and playGame().
playGame()
void playGame (struct ItemDetails * ptr, size_t nmemb)
Referenced by secureLoad().